### ISSUE TITLE
1.1.1 Additions

### ISSUE THREAD

**Issue by DrIOSX** [CriticalSolutionsNetwork/M365FoundationsCISReport#112]
### Tasks 

- [x] Add false to hybrid status. 

- [x] Add Global Reader to Check

- [x] Confirm Application Developer is an admin role.
```terminal
PS > $adminRoleNames = (Get-MgDirectoryRole | Where-Object { $null -ne $_.RoleTemplateId }).DisplayName        
PS > $adminRoleNames | sort
Application Developer
Azure AD Joined Device Local Administrator
Billing Administrator
Desktop Analytics Administrator
Directory Readers
Directory Synchronization Accounts
Directory Writers
Exchange Administrator
Global Administrator
Global Reader
Helpdesk Administrator
Intune Administrator
Knowledge Administrator
Knowledge Manager
License Administrator
Privileged Authentication Administrator
Privileged Role Administrator
Search Administrator
Security Reader
Service Support Administrator
SharePoint Administrator
Teams Administrator
User Administrator
```
- [x] Confirm the current list of admin roles in Entra.
